### ISSUE TITLE
[CLIENT] 감정 없애기 버튼 추가

### ISSUE THREAD

**Issue by suhyun22** [Medici-Mansion/EmoChat#12]
### 수정 요청

<img width="427" alt="스크린샷 2023-11-08 오후 7 10 48" src="https://github.com/Medici-Mansion/EmoChat/assets/112176958/8047b4d4-6895-4798-9b99-7e5d04d91581">

채팅방 우측 하단에 버튼을 생성하여 인식된 감정을 없애는 기능을 추가 요청드립니다.
추가하는 이유는 다른 표정을 지어도 감정이 빠르게 변경이 안되어서!

**Comment by raymondanythings** [comment]
@suhyun22 위치가 모바일에선 안보이는 위치일것 같은데 모바일은 고려 안해도 괜찮을까요?

**Comment by suhyun22** [comment]
@raymondanythings 네 어차피 모바일에선 작동을 안하더라구요? 괜찮을듯!
