### ISSUE TITLE
[QA] 실험 진행을 위한 서비스 완성

### ISSUE THREAD

**Issue by LeeBonHoon1** [Medici-Mansion/EmoChat#8]
### 수정 요청

프로필 수정 시 zod validation 추가
context info data로 default 값 세팅

**Comment by raymondanythings** [comment]
# QA 진행 후 추가 수정사항

@LeeBonHoon1 

- 다크모드: 사용자설정 취소버튼 안보임 
<img width="410" alt="image" src="https://github.com/Medici-Mansion/EmoChat/assets/73725736/84fc77e3-3d0c-46bf-a134-133082b1a205">
- 채팅방명 수정 드롭다운 스타일 사용자설정과 통일
<img width="286" alt="image" src="https://github.com/Medici-Mansion/EmoChat/assets/73725736/87028af3-4795-46ae-92db-a58cb0bad19f">

- 사용자 설정 최초 선택 아바타 -> 유저 아바타랑 다름
